#!/usr/bin/env bash
# delete-github-ssh-key
# Removes the SSH key for the current host from my GitHub account.
#
# Requires the environment variable BOOTSTRAP_GITHUB_TOKEN to be set.
#
# This used to clean up SSH keys generated during continuous integration
# tests.
main() {
	local -r github_token="$BOOTSTRAP_GITHUB_TOKEN"

	local -r hostname="$(hostname)" || return 1

	echo "Removing GitHub SSH key with title $hostname ..."

	local -r ssh_key_id=$(
		curl \
			-X GET \
			-H "Accept: application/vnd.github.v3+json" \
			-H "Authorization: token $github_token" \
			"https://api.github.com/user/keys" \
			| jq .[] \
			| jq --arg title "$hostname" 'select(.title == $title)' \
			| jq .id
	) || return 1

	curl \
		-X DELETE \
		-H "Accept: application/vnd.github.v3+json" \
		-H "Authorization: token $github_token" \
		"https://api.github.com/user/keys/$ssh_key_id" \
		|| return 1

	echo "Removed GitHub SSH key with title $hostname."
	return 0
}

main $@
